### ISSUE TITLE
Use of op cli for vs-code devcontainer setup.sh script

### ISSUE THREAD

**Issue by nick-youngblut** [1Password/op-vscode#121]
### Summary

It appears that there are no docs on using the `op` cli for injecting secrets in a devcontainer `setup.sh` script (the `"postCreateCommand"` in the `devcontainer.json`). It would be helpful to have docs on best-practices for that scenario. 

### Use cases

I currently have the following in my `setup.sh` script for my devcontainer:

```
curl -sS https://downloads.1password.com/linux/keys/1password.asc | \
  sudo gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/$(dpkg --print-architecture) stable main" |
  sudo tee /etc/apt/sources.list.d/1password.list
sudo mkdir -p /etc/debsig/policies/AC2D62742012EA22/
curl -sS https://downloads.1password.com/linux/debian/debsig/1password.pol | \
  sudo tee /etc/debsig/policies/AC2D62742012EA22/1password.pol
sudo mkdir -p /usr/share/debsig/keyrings/AC2D62742012EA22
curl -sS https://downloads.1password.com/linux/keys/1password.asc | \
  sudo gpg --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
sudo apt update && sudo apt install 1password-cli
eval $(op signin)
# I then have to manually type in 4 items of information in order to complete the login 

AWS_ACCESS_KEY_ID=`op read op://Private/AWS/username`
AWS_SECRET_ACCESS_KEY=`op read op://Private/AWS/credential`
AWS_DEFAULT_REGION=`op read op://Private/AWS/region` 
mkdir -p ~/.aws/
cat <<-END > ~/.aws/credentials
[default]
aws_access_key_id = $AWS_ACCESS_KEY_ID
aws_secret_access_key = $AWS_SECRET_ACCESS_KEY
region = $AWS_DEFAULT_REGION
END
chmod 600 ~/.aws/credentials
```

### Proposed solution

It would be great to have some docs on whether the above method is best-practices or whether there is a better way. AFAIK, the VS Code extension cannot be used during the `postCreateCommand` job, but maybe I'm wrong?

### Is there a workaround to accomplish this today?

See above

**Comment by rafalmasiarek** [comment]
Hej @nick-youngblut  
I came here from a google because I thought the same thing about taking AWS credentials from 1password to a devcontianer
but my idea is try do this with plugin https://developer.1password.com/docs/cli/shell-plugins/aws/  (I haven't tested this yet)
maybe this help you or have you already rejected this solution?

**Comment by jodyheavener** [comment]
Hey @nick-youngblut! Thanks for filing this issue. I'm not entirely sure if VS Code extensions can be set up this way, however if you're trying to use the AWS CLI you might be better off with what @rafalmasiarek has suggested by using our Shell Plugin for AWS. I'm curious to hear if this works for you, or if there's another scenario you're trying to make work. Thank you!

**Comment by nick-youngblut** [comment]
Thanks @rafalmasiarek and @jodyheavener for the feedback! I'll have to do some experimentation to see what works best

**Comment by jodyheavener** [comment]
Hi there! We're just doing some housekeeping and it looks like this issue is either largely resolved or not within scope of the project. If you feel this is incorrect please re-open or file a new issue. Thank you!
