### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by BitesizedLion** [1Password/op-vscode#16]
Hey there, huge fan of 1Password.

I don't seem to be able to login, or figure out how. 

I have the CLI installed, logged in with `Invoke-Expression $(op signin)` using Powershell without any issues.
However once I go into VSCode, I do F1 -> `Choose Account` and pick the account, it shows
`Error executing CLI command: You are not currently signed in. Please run op signin --help for instructions.`

I am not using Biometric Unlock by the way (which I assume isn't required since [the docs say so](https://developer.1password.com/docs/vscode/#:~:text=If%20you%20don%27t%20have%20a%20biometric%20device%2C%20you%27ll%20still%20be%20able%20to%20use%20your%20device%20user%20password.)).

OP Version: 2.4.1
OP-VSCode Version: 0.1.1
OS: Windows 10 (21H1)
1Password Version: 8.7.2

**Comment by jodyheavener** [comment]
Hey @BitesizedLion, thanks for reaching out. For the time being biometric unlock is [required](https://developer.1password.com/docs/vscode/#requirements) to use the extension. We're looking into to ways to remove this requirement, so stay tuned. I'll also note that you don't actually need a biometric device to enable this feature in case you still want to try it out (you'll still be able to use your device user password).

**Comment by BitesizedLion** [comment]
@jodyheavener Thanks for the quick reply and clarification that I can enable the feature without having a biometric device. 👍

I was quite confused that the docs said you needed biometric unlock but also at the same time said you didn't need a biometric device and I was also under the impression that to enable the feature I'd need a biometric device.

I've gone ahead and purchased a fingerprint reader any way, to make my life easier.
