### ISSUE TITLE
Example of build tasks that op inject before source files with secrets compiled

### ISSUE THREAD

**Issue by watou** [1Password/op-vscode#161]
### Summary

An example is much needed to show how a source file, such as a `config.h` header file containing secret references, could be used at build time in VS Code.  As it is, secret references are compiled into the binary, not the secrets they reference.  I can envision there being a set of build tasks that take a `config.h.tpl` file, use `op inject` to create the `config.h` file, conduct the rest of the build, and then delete the `config.h` file in all cases at the end.

### Use cases

A need to inject secrets at build time is pretty obvious, but the ways in which it can be accomplished are murky and require more knowledge that would be ideally presented as an example with this project.  There is no evidence from available documentation that this important feature is present in this project, perhaps because it cannot be solved generically without regard to the code project's specifics.

### Proposed solution

A person with VS Code expertise would offer a clear and concise example of secret injection at build time in VS Code in conjunction wirth this extension.

### Is there a workaround to accomplish this today?

Manual steps at a command line outside of VS Code of `op inject` before builds and `rm` after.

**Comment by jodyheavener** [comment]
Thanks for opening this @watou! To clarify, you're asking for some documentation on how one might set up build tasks to execute a set of commands that include `op inject` as a step so that the actual secret is injected, is that correct? I think we could do something like that over on our [developer portal's documentation](https://developer.1password.com/docs/vscode/).

**Comment by watou** [comment]
A complete VS Code project example provided in the documentation that shows the complete use case where the fully demonstrated value of op-vscode is clearly illustrated and explained.  The example should not leave out "cleaning up secrets written to disk" as an exercise for the reader, nor leave out any other aspect that would skip a critical aspect of a complete use case example.  Surely anyone who actually gets any value from this integration would have such an example in nearly ready-to-go condition?

**Comment by jodyheavener** [comment]
Thanks for your response @watou. I'd still like to clarify your request around build tasks specifically, if you don't mind, as the extension has considerable other benefits beyond that. Would you be able to elaborate on what you're looking for?

**Comment by watou** [comment]
How about this? "Make a VS Code project that demonstrates all of the considerable benefits of the op-vscode extension, in a complete, coherent way that teaches us developers how to practically use all of the considerable features and benefits of the extension, while not failing to include all practical necessities, such as injecting secerts during a VS Code build and not leaving injected secrets written to disk, nor failing to address any of the aspects of usability that would be important in a properly secure usage of the extension in a VS Code project."

So if the extension merely inserts secret references into code and everything related, what next for the developer?  Obviously, building in such a way to make use of these secret references.  I spent so much time trying to find any help in the VS Code context and was only told "you're looking for op inject."  No, I'm looking for an example VS Code project that demonstrates proper use of injected secret references during a VS Code build.  I thought this would be obvious in the context of a VS Code extension.  I have no further way of explaining this.

**Comment by jodyheavener** [comment]
Hi @watou, thanks again for your feedback here! I agree that more can be done to further outline the benefits and use cases for the extension, and in talking with the team we're going to look at how this can be improved all around. In the meantime I will point you to our [CLI docs](https://developer.1password.com/docs/cli/) as well, as it is used in conjunction with the extension to go from working in the code to executing it. I am going to close this ticket now while we work on how to scope these changes. Thanks again for your input here.

**Comment by watou** [comment]
Totally predictable punt!
