### ISSUE TITLE
how to execute code having 1Password reference

### ISSUE THREAD

**Issue by sfc-gh-smisra** [1Password/op-vscode#163]
Hi Team,

The documentation doesn't clarify how to run a script, if it has a secret reference. Every time I try to run the script with **op run** prefix , it fails to load the actual value of the secret at runtime

**Comment by jodyheavener** [comment]
Hi @sfc-gh-smisra, thanks for filing this issue. The VS Code extension can help you insert references into the code you're working on, but is not directly responsible for executing code. For this you'll want to check the [documentation for `op run`](https://developer.1password.com/docs/cli/reference/commands/run) and how to use it in your terminal. I'm going to close this ticket as out of scope, but feel free to re-open or open a new ticket if I got something wrong here. Thank you!

**Comment by wichert** [comment]
I'm not sure the solution given here (use `op run`) is sufficient. For example I don't see how you can do that when you want to debug a rust crate, which takes a secret as argument.
