### ISSUE TITLE
Publish to open-vsx

### ISSUE THREAD

**Issue by svenefftinge** [1Password/op-vscode#33]
Hey I'm a co-founder at Gitpod 👋  

I'm currently writing a blog post on integrating 1password within a remote development setup.
I've stumbled over this extension and would love for our users to use it. Because MS restricts access to their marketplace to only MS and GitHub products, other Vs Code based products access the https://open-vsx.org alternative.

Would it be possible to also publish to open-vsx.org? It is fairly simple https://www.gitpod.io/blog/open-vsx#publishing

**Comment by jodyheavener** [comment]
Hey @svenefftinge, thanks for filing this. On the technical side this should be very easy considering we already use a GitHub Action that [supports this](https://github.com/HaaLeo/publish-vscode-extension#open-vsx-registry). I'll bring it up with the team for consideration. 😄

**Comment by florisvdg** [comment]
Also very curious to hear more about that blog post! Is that about the 1Password SSH Agent, the CLI, or the VS Code extension? Or all of them?

Fun fact: about a month ago I played around with Gitpod to see how it works with SSH agent forwarding. I ran into [an issue](https://github.com/gitpod-io/gitpod/issues/6993#issuecomment-1132230835) there, but that got fixed a few weeks ago. So this means that you can now SSH into a Gitpod workspace and then within the Gitpod workspace authenticate every Git or SSH request with Touch ID, without the private key ever leaving 1Password! This works pretty well and could even remove the hard requirement to [grant full OAuth repo access to Gitpod](https://github.com/gitpod-io/gitpod/issues/10362).
