### ISSUE TITLE
Unable to use with multiple accounts

### ISSUE THREAD

**Issue by thenbe** [1Password/op-vscode#88]
### Your environment

op-vscode version: 1.0.2

VS Code version: 1.71.2

CLI version: 2.7.1

OS: Ubuntu 22.04

## Steps to reproduce

1. Command Palette > `1password: choose acount` OR `1password: choose vault`
2. Choose one of the listed accounts.
  a. FWIW, both the listed acounts here have `my.1password.com` in light grey text displayed next to them.

## What happened?

vs code error toast popup:
`Error executing CLI command: found multiple accounts for filter "my.1password.com".`

## What did you expect to happen?

Be able to use one of the accounts. Be able to choose a vault belonging to one of the accounts

## Notes & Logs

```
["INFO" - 9:55:07 PM] Starting 1Password for VS Code.
["INFO" - 9:55:07 PM] Extension Version: 1.0.2.
["ERROR" - 9:55:15 PM] Error executing CLI command
```

**Comment by matthewsommer** [comment]
I'm having this issue. Does anyone know if there is a workaround?

**Comment by djvickery** [comment]
> label

Same issue here. Keen for a workaround

**Comment by phillipshaong** [comment]
Same issue. Any resolution?

**Comment by ericmoolin** [comment]
Also experiencing the same issue, any chance of seeing this bug get fixed soon?

**Comment by jodyheavener** [comment]
Thanks all for filing and chiming in on this issue. I _think_ the fix here could be to set the [account flag](https://github.com/1Password/op-vscode/blob/main/src/setup.ts#L32) to a User ID as opposed to the Account URL. Some exploration is needed. The team will try to get to this soon, but it's considered open to work on if anyone is up for it.

**Comment by cabralje** [comment]
Same issue here

**Comment by grunwalski** [comment]
Any news on it? This bug is getting ready for its 3rd birthday.

> Thanks all for filing and chiming in on this issue. I _think_ the fix here could be to set the [account flag](https://github.com/1Password/op-vscode/blob/main/src/setup.ts#L32) to a User ID as opposed to the Account URL, which is supported by the [global flags](https://developer.1password.com/docs/cli/reference#global-flags). Some exploration is needed. The team will try to get to this soon, but it's considered open to work on if anyone is up for it.

**Comment by swift-develop** [comment]
Have the same issue.

**Comment by ericmoolin** [comment]
If anyone is still experiencing issues with this, sign out of your accounts on the desktop app and sign back in. Make sure when you do the browser sign in that each account your signing into is using a unique subdomain. Example yourbusiness.1password.com. For some reason my personal and my work account had both been registered into the app with my.1password.com which was causing the conflict.
